README, test fixes

diff --git a/dapp_cmd b/dapp_cmd
--- a/dapp_cmd
+++ b/dapp_cmd
@@ -287,9 +287,12 @@ set_dcd_target() {
 
 set_dcd_var() {
         DCD_CMD="$(cat <<'EOF'
-dcd() { cd "$(dapp "$1" path)"; }
+dcd() {                 #### AUTO GENERATED BY 'dapp' ####
+    cd "$(dapp "$1" path)";
+}
 
-_dcd_completions() {
+_dcd_completions() {    #### AUTO GENERATED BY 'dapp' ####
+
     local curr_word="${COMP_WORDS[COMP_CWORD]}"
 
     if [ "$COMP_CWORD" -eq 1 ]; then
@@ -366,7 +369,7 @@ ${inject:-}
 EOF
 
     if ! yn_answer "Install 'dcd' command"; then
-        echo "Aborting dcd installation"
+        echo "Aborting..."
         exit 1
     fi
 
@@ -376,14 +379,29 @@ EOF
     local BRC="$_DCD_TARGET"
 
     if [[ ! -f "$BRC" ]]; then
+        local bn
+        bn="$(basename "$BRC")"
+
+        echo "You do not appear to have a ${bn} file."
+        echo "dcd requires a ${bn} file to work."
+
         log "$BRC does not exist; creating"
-        touch "$BRC" || {
-            echo "$BRC cannot be created, installation failed"
+
+        if ! yn_answer "Do you want me to create a ${bn} file for you"; then
+            echo "Aborting..."
             exit 1
-        }
+        fi
+
+        if ! touch "$BRC"; then
+            err "dcd: $BRC cannot be created, installation failed"
+            exit 1
+        else
+            echo "dcd: Created, $BRC"
+        fi
     fi
 
     log "Appending dcd function to $BRC"
+    echo "dcd: Writing to $BRC"
     printf "%s\n" "" >> "$BRC"
     printf "%s\n" "$line" >> "$BRC"
 
@@ -421,7 +439,7 @@ uninstall_dcd() {
 
         echo "✅ dcd: Function removed for $user, user must logout to complete."
     else
-        err "dcd: Not installed for user, in $BRC"
+        info "dcd: Dependancy missing, $BRC"
     fi
 }
 
@@ -603,6 +621,7 @@ install_self() {
     fi
 
     # Run 'dapp --autocomplete' then place code in completion folder
+    echo "autocomple -> $completion_dir/dapp"
     if ! "$target" --autocomplete | tee "$completion_dir/dapp" >/dev/null; then
         err "Warning: Autocomplete registration failed; continuing without completion."
         err "Check permissions for $completion_dir or set DAPP_COMPLETION_DIR to a writable path."
@@ -662,7 +681,7 @@ uninstall_self() {
         err "Failed to remove completion code , $completion_dir/dapp"
         exit 1
     fi
-
+    complete -r dapp 2>&1 /dev/null
     echo "✅ dapp uninstall completed successfully."
 }
 
